publish_dir: gp-site
output:
  md_document:
    variant: markdown_github
    preserve_yaml: true
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
