remote_theme: pages-themes/hacker@v0.2.0
title: Token Narratives
description: Token Narrative Compiler and API

google_analytics: 

output:
  md_document:
    variant: markdown_github
    preserve_yaml: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge  

baseurl: /gp-site
url: https://bagnuss.github.io/token-narratives
publish_dir: gp-site

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts