
title: Token Narratives
email: bagnusscom@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  Tracking speculative crypto narratives. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bagnuss
github_username:  bagnuss
#### WORKING ####
# theme: jekyll-theme-hacker
#### WORKING ####
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#### NEW ####

#### NEW ####

plugins:
  - jekyll-feed
